Propose new recommended community policy R7
xsdk-project/xsdk-community-policies pull request #4
Opened 2019-05-28 14:10 UTC by ulrikeyang

Due to a request by the facilities for a well defined space on package information, we are in the process of formulating a new recommended community policy. This is a first preliminary draft to get the process started.

2019-05-30 16:21 UTC, balay commented
Perhaps README.md  name should also acceptable.

Here are some relavent docs wrt README at github, bitbucket, gitlab

https://help.github.com/en/articles/about-readmes
https://confluence.atlassian.com/bitbucket/display-readme-text-on-the-overview-221449772.html
https://docs.gitlab.com/ee/user/markdown.html

Bitbucket is listing a bunch of other acceptable extensions to README. Gitlab mentions a bunch of acceptable locations for this file.

2019-05-30 21:47 UTC, maherou commented
I would be inclined to prefer the .md version of these files in order to support formatted text. 

Also, in addition to the README.md and LICENSE.md files, I would like to have us consider files like SUPPORT.md, CONTRIBUTING.md and others.  Facilities staff want to know much more about our products than what they would find in the readme and license files.  Here is some more details about what other people have considered:  https://github.com/kmindi/special-files-in-repository-root/blob/master/README.md

We should come up with a list of these files and then have them reviewed by people like Judy Hill and Katherine Riley and their teams.

2019-06-07 15:34 UTC, ulrikeyang commented
I have revised the proposed recommended community policy based on discussions we had at yesterday's xSDK meeting.

2019-06-07 16:25 UTC, balos1 commented
The short-form of this policy should also be added to the `package_policies/README.md` file (and linked to the R7.md file like the others).

2019-06-13 21:38 UTC, acfisher approved these changes

2019-06-13 22:12 UTC, ulrikeyang commented
Rebecca Hartman-Baker of NERSC asks if we could include a pointer to how to install with spack in the installation instructions.

So, we could add '(including pointers on how to install with spack)' after 'information on how to install the package.'

2019-06-13 22:21 UTC, maherou commented
It seems to me that we should start with a fairly long list potential informational files.  To address this particular request, could we have a file named INSTALLATION.md or INSTALLING.md or something similar?

Brainstorming on potential files beyond what is already commonly used can be a good part of the discussion.

On Jun 14, 2019, at 12:12 AM, ulrikeyang <notifications@github.com<mailto:notifications@github.com>> wrote:


Rebecca Hartman-Baker of NERSC asks if we could include a pointer to how to install with spack in the installation instructions.

So, we could add '(including pointers on how to install with spack)' after 'information on how to install the package.'

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/xsdk-project/xsdk-community-policies/pull/4?email_source=notifications&email_token=AAHZISYRTPF6GU43EE7GLE3P2LA5TA5CNFSM4HQDZWO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXVFUAI#issuecomment-501897729>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAHZIS7UFGXPR4FBAJKYM2DP2LA5TANCNFSM4HQDZWOQ>.

2019-06-13 22:51 UTC, ulrikeyang commented
How is installation information handled by other libraries?
Btw, hypre has a INSTALL.md file in the top directory with installation information, so I don’t mind adding INSTALL or INSTALL.md to the list 😊.

In general, I would however prefer to keep the number of files limited.


From: Mike Heroux <notifications@github.com>
Sent: Thursday, June 13, 2019 3:21 PM
To: xsdk-project/xsdk-community-policies <xsdk-community-policies@noreply.github.com>
Cc: Yang, Ulrike Meier <yang11@llnl.gov>; Author <author@noreply.github.com>
Subject: Re: [xsdk-project/xsdk-community-policies] Propose new recommended community policy R7 (#4)

It seems to me that we should start with a fairly long list potential informational files. To address this particular request, could we have a file named INSTALLATION.md or INSTALLING.md or something similar?

Brainstorming on potential files beyond what is already commonly used can be a good part of the discussion.

On Jun 14, 2019, at 12:12 AM, ulrikeyang <notifications@github.com<mailto:notifications@github.com>> wrote:


Rebecca Hartman-Baker of NERSC asks if we could include a pointer to how to install with spack in the installation instructions.

So, we could add '(including pointers on how to install with spack)' after 'information on how to install the package.'

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/xsdk-project/xsdk-community-policies/pull/4?email_source=notifications&email_token=AAHZISYRTPF6GU43EE7GLE3P2LA5TA5CNFSM4HQDZWO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXVFUAI#issuecomment-501897729>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAHZIS7UFGXPR4FBAJKYM2DP2LA5TANCNFSM4HQDZWOQ>.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/xsdk-project/xsdk-community-policies/pull/4?email_source=notifications&email_token=AD4NLLJBERKV3SL4ANKQZATP2LB47A5CNFSM4HQDZWO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXVGEQY#issuecomment-501899843>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AD4NLLNTJFCKDPY6YRG2B2TP2LB47ANCNFSM4HQDZWOQ>.

2019-06-14 01:05 UTC, xiaoyeli commented
I am fine with this.  Currently for SuperLU, the installation instructions are also in README.md.

2019-06-14 02:55 UTC, jthies approved these changes

2019-06-14 03:07 UTC, balay commented
> Rebecca Hartman-Baker of NERSC asks if we could include a pointer to how to install with spack in the installation instructions.
> 
> So, we could add '(including pointers on how to install with spack)' after 'information on how to install the package.'

I don't think installation instructions is the correct place for spack specific info - the same way most packages don't have ubuntu or fedora, or RHEL - or brew installation instructions.

Once you know these package managers,  all packages are equivalent wrt installation. So its more of learning spack - and 'spack insallation instructions [within package installation instructiosn] are not a substitute.

However - some packages do mention such info on their download web-page. i.e One can get the tarball - and install from source - or use package manager from their favourite distribution to download/install the package etc.

2019-06-14 05:28 UTC, maherou commented
Thanks for these comments.  My point is that we should thoroughly explore the space of potential information and then cut down to the essentials.  I think this model of using .md files in the repository is an excellent way to convey basic content about a product.  We should use it for any content that is specific.

Regarding spack, I like @balay comments about homebrew, etc.  Would it be useful to have the Spack package name accessible from one of these files?  For many products, the package name may be obvious, but not for all.

2019-06-14 06:27 UTC, tzanio approved these changes

2019-06-14 07:58 UTC, hartwiganzt commented
Maybe it would make sense to note that it is OK  to provide detailed instructions in another file and reference that file from the README.md. But the way it is worded one can argue that this is already permitted.

2019-06-14 16:20 UTC, mkstoyanov approved these changes

2019-06-14 16:20 UTC, mkstoyanov commented on package_policies/R7.md
> +- contact information, i.e. how to get help (**M5**)
Do we have to put our e-mails into the public GitHub README?

Isn't it enough that the README has a link to the web-page and the web-page has the contact e-mail.

2019-06-14 16:25 UTC, balay commented on package_policies/R7.md
> +- contact information, i.e. how to get help (**M5**)
I think you can repeat the URL in the 'Contact' section of README

2019-06-14 16:57 UTC, balay commented
>  Would it be useful to have the Spack package name accessible from one of these files? For many products, the package name may be obvious, but not for all.

I think its easier to get this [and other spack related] info directly from `spack`

```
$ spack help list
list and search available packages
<snip>
balay@sb /home/balay
$ spack list trilinos
==> 3 packages.
trilinos  trilinos-catalyst-ioss-adapter  xsdktrilinos
balay@sb /home/balay
$ spack list -d petsc
==> 5 packages.
petsc  phist  py-petsc4py  sowing  xsdktrilinos
balay@sb /home/balay
$ spack info py-petsc4py
PythonPackage:   py-petsc4py
<snip>
```
etc..

2019-06-15 02:33 UTC, xiaoyeli approved these changes

2019-06-17 16:30 UTC, ulrikeyang commented
I think the full installation information in the README file or a link to where the full installation information is found (which could be a INSTALL file) would be fine. We can reword this to make this clear.

2019-06-20 21:49 UTC, balay commented on package_policies/R7.md
> +The CHANGELOG file should contain important changes or a link to a file or webpage with this information, but not each individual commit.
`but not each individual commit` -> `but not a list of all individual commit messages`

2019-06-20 21:51 UTC, balay commented on package_policies/R7.md
> +The CHANGELOG file should contain important changes or a link to a file or webpage with this information, but not each individual commit.
or:
 `but not each individual commit message`

2019-06-21 14:54 UTC, balay approved these changes

2019-06-21 17:09 UTC, acfisher approved these changes

2019-06-21 19:59 UTC, mkstoyanov approved these changes

2019-06-23 17:25 UTC, balos1 requested changes
@ulrikeyang I approve of the changes, but I think the short version of the policy needs to be added to the `package_policies/README.md` file before the PR is merged.

2019-06-24 19:57 UTC, balay commented
> @ulrikeyang I approve of the changes, but I think the short version of the policy needs to be added to the `package_policies/README.md` file before the PR is merged.

Perhaps the following change?
```
diff --git a/package_policies/README.md b/package_policies/README.md
index a331169..307b681 100644
--- a/package_policies/README.md
+++ b/package_policies/README.md
@@ -102,6 +102,8 @@ In addition to the required xSDK policies listed above, the following capabiliti
 
 **R6.** [Document versions of packages that it works with or depends upon, preferably in machine-readable form.](/package_policies/R6.md)
 
+**R7.** [Document package information in README and related files.](/package_policies/R7.md)
+
 ## History of the xSDK Community Policies
 
 The original version of this document was prepared in 2015 by Barry Smith with key input from Roscoe Bartlett
```

2019-06-24 20:46 UTC, balos1 approved these changes

2019-06-27 18:06 UTC, osborn9 approved these changes

2019-06-27 18:08 UTC, jwillenbring approved these changes

2019-06-27 18:13 UTC, luszczek approved these changes

2019-06-27 18:18 UTC, merged